const STORAGE_KEY='mis-propinas-v1';
const stored=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');
let records=Array.isArray(stored)?stored:(stored.records||[]);
let days=Array.isArray(stored?.days)?stored.days:[];
let activeDayId=stored?.activeDayId||null;
let tipMode='percent';
let editingId=null;
let editMode='percent';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n)||0);
const number=v=>Number(String(v).replace(',','.'))||0;
const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateLabel=date=>new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short'}).format(new Date(`${date}T12:00:00`));
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({records,days,activeDayId}));}
function ensureDay(){records=records.map(r=>({...r,dayId:r.dayId||`legacy-${r.date}`}));const legacyDates=[...new Set(records.filter(r=>r.dayId.startsWith('legacy-')).map(r=>r.date))];legacyDates.forEach(date=>{const id=`legacy-${date}`;if(!days.some(d=>d.id===id))days.push({id,date,createdAt:0})});if(!days.length){days=[{id:`day-${Date.now()}`,date:todayKey(),createdAt:Date.now()}];activeDayId=days[0].id}if(!activeDayId||!days.some(d=>d.id===activeDayId))activeDayId=days[0].id;save();}
function calculate(){const bill=number($('billTotal').value), raw=number($('tipValue').value), tip=tipMode==='percent'?bill*raw/100:raw, house=bill*.05;return {bill,tip,house,net:tip-house,percent:bill?tip/bill*100:0};}
function renderLive(){const c=calculate();$('liveGross').textContent=money(c.tip);$('liveHouse').textContent=money(c.house);$('liveNet').textContent=money(c.net);$('liveNet').classList.toggle('negative',c.net<0);}
function render(){const current=days.find(d=>d.id===activeDayId)||days[0], selected=records.filter(r=>r.dayId===activeDayId);const tips=selected.reduce((s,r)=>s+r.tip,0), house=selected.reduce((s,r)=>s+r.house,0), net=tips-house;$('summaryTitle').innerHTML=`${money(net)} <span>neto</span>`;$('summaryTips').textContent=money(tips);$('summaryHouse').textContent=money(house);$('summaryCount').textContent=selected.length;$('todayLabel').textContent=current?dateLabel(current.date):dateLabel(todayKey());$('clearButton').classList.toggle('hidden',!records.length);$('emptyState').classList.toggle('hidden',!!selected.length);$('history').innerHTML=selected.map(r=>`<article class="history-item"><div><div class="title">${money(r.bill)} de cuenta</div><div class="detail">${r.percent.toFixed(1).replace('.0','')}% · ${money(r.tip)} propina · ${money(r.house)} caja</div></div><div><div class="net ${r.net<0?'negative':''}">${money(r.net)}</div><div class="time">${r.time}</div></div><div class="record-actions"><button type="button" class="text-button edit-record" data-id="${r.id}">Editar</button><button type="button" class="text-button delete-record" data-id="${r.id}">Borrar</button></div></article>`).join('');const oldDays=days.filter(d=>d.id!==activeDayId).sort((a,b)=>b.createdAt-a.createdAt);$('daysSection').classList.toggle('hidden',!oldDays.length);$('daysList').innerHTML=oldDays.map(d=>`<button class="day-chip" type="button" data-day="${d.id}">${dateLabel(d.date)}</button>`).join('');document.querySelectorAll('.day-chip').forEach(b=>b.addEventListener('click',()=>{activeDayId=b.dataset.day;save();render()}));document.querySelectorAll('.edit-record').forEach(b=>b.addEventListener('click',()=>openEdit(Number(b.dataset.id))));document.querySelectorAll('.delete-record').forEach(b=>b.addEventListener('click',()=>deleteRecord(Number(b.dataset.id))));}
document.querySelectorAll('.segment').forEach(b=>b.addEventListener('click',()=>{tipMode=b.dataset.mode;document.querySelectorAll('.segment').forEach(x=>x.classList.toggle('active',x===b));$('tipPrefix').textContent=tipMode==='percent'?'%':'$';$('tipValue').placeholder=tipMode==='percent'?'0':'0.00';$('tipHelp').textContent=tipMode==='percent'?'Escribe el porcentaje que te dejaron.':'Escribe cuánto dinero te dejaron de propina.';renderLive();}));
['billTotal','tipValue'].forEach(id=>$(id).addEventListener('input',renderLive));
$('tipForm').addEventListener('submit',e=>{e.preventDefault();const c=calculate();if(c.bill<=0||c.tip<0){showToast('Revisa los datos ingresados');return}records.unshift({id:Date.now(),dayId:activeDayId,date:todayKey(),time:new Intl.DateTimeFormat('es-MX',{hour:'numeric',minute:'2-digit'}).format(new Date()),...c});save();e.target.reset();renderLive();render();showToast('Registro guardado');});
$('newDayButton').addEventListener('click',()=>{activeDayId=`day-${Date.now()}`;days.unshift({id:activeDayId,date:todayKey(),createdAt:Date.now()});save();render();showToast('Nuevo día iniciado');});
$('clearButton').addEventListener('click',()=>{if(confirm('¿Borrar todos los registros guardados en este dispositivo?')){records=[];days=[];activeDayId=null;ensureDay();render();showToast('Historial borrado');}});
function editCalculate(){const bill=number($('editBill').value),raw=number($('editTip').value),tip=editMode==='percent'?bill*raw/100:raw,house=bill*.05;return {bill,tip,house,net:tip-house,percent:bill?tip/bill*100:0};}
function renderEditPreview(){const c=editCalculate();$('editGross').textContent=money(c.tip);$('editHouse').textContent=money(c.house);$('editNet').textContent=money(c.net);$('editNet').classList.toggle('negative',c.net<0);}
function syncEditMode(){document.querySelectorAll('#editPercent,#editMoney').forEach(b=>b.classList.toggle('active',(b.id==='editPercent')=== (editMode==='percent')));$('editPrefix').textContent=editMode==='percent'?'%':'$';}
function openEdit(id){const r=records.find(x=>x.id===id);if(!r)return;editingId=id;editMode='percent';$('editBill').value=r.bill;$('editTip').value=Number(r.percent.toFixed(2));syncEditMode();renderEditPreview();$('editDialog').showModal();}
function deleteRecord(id){if(!confirm('¿Quieres borrar este registro? Esta acción no se puede deshacer.'))return;records=records.filter(r=>r.id!==id);save();render();showToast('Registro borrado');}
['editBill','editTip'].forEach(id=>$(id).addEventListener('input',renderEditPreview));
$('editPercent').addEventListener('click',()=>{editMode='percent';syncEditMode();renderEditPreview()});$('editMoney').addEventListener('click',()=>{editMode='money';syncEditMode();renderEditPreview()});$('closeEditDialog').addEventListener('click',()=>$('editDialog').close());$('editForm').addEventListener('submit',e=>{e.preventDefault();const c=editCalculate();if(c.bill<=0||c.tip<0){showToast('Revisa los datos ingresados');return}const r=records.find(x=>x.id===editingId);if(r)Object.assign(r,c);save();$('editDialog').close();render();showToast('Registro actualizado');});
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('howButton').addEventListener('click',()=>$('howDialog').showModal());$('closeDialog').addEventListener('click',()=>$('howDialog').close());
let deferredPrompt;$('installButton').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installButton').classList.add('hidden')}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installButton').classList.remove('hidden')});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw-v4.js');ensureDay();renderLive();render();
